#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SQLite.Resource", IsApplication=true)]

namespace SQLite
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int clublogo81 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Eredivisielogo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060017
			public const int Draws = 2131099671;
			
			// aapt resource value: 0x7f06001b
			public const int GoalDifference = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int GoalsAgainst = 2131099674;
			
			// aapt resource value: 0x7f060019
			public const int GoalsFor = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int Loss = 2131099672;
			
			// aapt resource value: 0x7f060015
			public const int MatchesPlayed = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int Name = 2131099668;
			
			// aapt resource value: 0x7f06001c
			public const int Points = 2131099676;
			
			// aapt resource value: 0x7f060028
			public const int Profieltxt = 2131099688;
			
			// aapt resource value: 0x7f060039
			public const int STANDINGSLIST = 2131099705;
			
			// aapt resource value: 0x7f060016
			public const int Wins = 2131099670;
			
			// aapt resource value: 0x7f060003
			public const int ajax = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int az = 2131099652;
			
			// aapt resource value: 0x7f06001e
			public const int back = 2131099678;
			
			// aapt resource value: 0x7f060000
			public const int btnGetData = 2131099648;
			
			// aapt resource value: 0x7f060027
			public const int btn_reg_create = 2131099687;
			
			// aapt resource value: 0x7f060023
			public const int btnlogin = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int btnregister = 2131099684;
			
			// aapt resource value: 0x7f06001f
			public const int compare = 2131099679;
			
			// aapt resource value: 0x7f060001
			public const int container = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int denhaag = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int excelsior = 2131099660;
			
			// aapt resource value: 0x7f060005
			public const int feyenoord = 2131099653;
			
			// aapt resource value: 0x7f06000d
			public const int groningen = 2131099661;
			
			// aapt resource value: 0x7f060009
			public const int heerenveen = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int heracles = 2131099659;
			
			// aapt resource value: 0x7f060032
			public const int imageView1 = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int linearLayout1 = 2131099699;
			
			// aapt resource value: 0x7f060036
			public const int linearLayout2 = 2131099702;
			
			// aapt resource value: 0x7f060034
			public const int menuButton = 2131099700;
			
			// aapt resource value: 0x7f06000f
			public const int nac = 2131099663;
			
			// aapt resource value: 0x7f060029
			public const int profielknop1 = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int profielknop2 = 2131099690;
			
			// aapt resource value: 0x7f060002
			public const int psv = 2131099650;
			
			// aapt resource value: 0x7f06001d
			public const int relativeLayout1 = 2131099677;
			
			// aapt resource value: 0x7f060011
			public const int roda = 2131099665;
			
			// aapt resource value: 0x7f060037
			public const int searchBar = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int searchButton = 2131099704;
			
			// aapt resource value: 0x7f060012
			public const int sparta = 2131099666;
			
			// aapt resource value: 0x7f060031
			public const int startknop = 2131099697;
			
			// aapt resource value: 0x7f060020
			public const int textView1 = 2131099680;
			
			// aapt resource value: 0x7f060035
			public const int title = 2131099701;
			
			// aapt resource value: 0x7f060013
			public const int twente = 2131099667;
			
			// aapt resource value: 0x7f060026
			public const int txt_reg_password = 2131099686;
			
			// aapt resource value: 0x7f060025
			public const int txt_reg_username = 2131099685;
			
			// aapt resource value: 0x7f060030
			public const int txtclub = 2131099696;
			
			// aapt resource value: 0x7f06002c
			public const int txtleeftijd = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int txtlengte = 2131099693;
			
			// aapt resource value: 0x7f06002f
			public const int txtmarkt = 2131099695;
			
			// aapt resource value: 0x7f06002b
			public const int txtnaam = 2131099691;
			
			// aapt resource value: 0x7f06002e
			public const int txtpositie = 2131099694;
			
			// aapt resource value: 0x7f060022
			public const int txtpwd = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int txtusername = 2131099681;
			
			// aapt resource value: 0x7f060006
			public const int utrecht = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int vitesse = 2131099655;
			
			// aapt resource value: 0x7f060010
			public const int vvv = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int willem = 2131099662;
			
			// aapt resource value: 0x7f06000a
			public const int zwolle = 2131099658;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Clubdata = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Clubs = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ClubStandingDetail = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Newuser = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Profiel = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int row = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int start = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Uitslagen = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int Spelers = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
